# profile.ps1 - pwsh-tools entry point
# This file is dot-sourced on every interactive PowerShell start.
#
# Framework initialization happens below.
# DO NOT edit this file for personal customizations --
# instead, create C:\pwsh-tools\custom.ps1 (gitignored) or add code
# inside the User Customization region at the bottom of this file.

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Continue'

# --- Framework Initialization ---

# Dot-source the module loader
. "$PSScriptRoot\loader.ps1"

# Startup hint
if ($env:PWSH_TOOLS_QUIET -ne '1') {
    Write-Host "  pwsh-tools - Run 'Show-Manual' for available commands." -ForegroundColor DarkGray
}

# --- End Framework Initialization ---


#region User Customization
# =============================================================================
# Add your personal PowerShell customizations below this line.
# This region is preserved across pwsh-tools updates.
#
# Alternatively, create C:\pwsh-tools\custom.ps1 -- it is sourced
# automatically if it exists, and is gitignored so it stays local.
# =============================================================================



#endregion User Customization


# --- Source user customization file (optional, gitignored) ---
if (Test-Path "$PSScriptRoot\custom.ps1") {
    . "$PSScriptRoot\custom.ps1"
}
